call npm link del
call npm link gulp
call npm link gulp-autoprefixer
call npm link gulp-batch
call npm link gulp-clean-css
call npm link gulp-concat
call npm link gulp-csscomb
call npm link gulp-folders
call npm link gulp-group-css-media-queries
call npm link gulp-ignore
call npm link gulp-imagemin
call npm link gulp-less
call npm link gulp-load-plugins
call npm link gulp-notify
call npm link gulp-plumber
call npm link gulp-rename
call npm link gulp-rigger
call npm link gulp-sass
call npm link gulp-sourcemaps
call npm link gulp-strip-css-comments
call npm link gulp-uglify
call npm link gulp-util
call npm link gulp.spritesmith
call npm link imagemin-mozjpeg
call npm link imagemin-pngquant
call npm link imagemin-svgo
call npm link merge-stream
call npm link path
call npm link rigger
